spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: always
  session:
    timeout: 900 # 15분
  data:
    web:
      pageable:
        default-page-size: 15

server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    org.hibernate.SQL: debug